// Code generated by go-swagger; DO NOT EDIT.

// Package restapi elephpants-api
//
//	HTTP server that handle cute Elephpants.
//	Schemes:
//	  http
//	Host: localhost:8080
//	BasePath: /
//	Version: 0.1.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - image/png
//	  - application/json
//	  - text/plain
//
// swagger:meta
package restapi
