// Code generated by go-swagger; DO NOT EDIT.

package elephpants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteElephpantOKCode is the HTTP code returned for type DeleteElephpantOK
const DeleteElephpantOKCode int = 200

/*
DeleteElephpantOK OK

swagger:response deleteElephpantOK
*/
type DeleteElephpantOK struct {
}

// NewDeleteElephpantOK creates DeleteElephpantOK with default headers values
func NewDeleteElephpantOK() *DeleteElephpantOK {

	return &DeleteElephpantOK{}
}

// WriteResponse to the client
func (o *DeleteElephpantOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteElephpantNotFoundCode is the HTTP code returned for type DeleteElephpantNotFound
const DeleteElephpantNotFoundCode int = 404

/*
DeleteElephpantNotFound A elephpant with the specified Name was not found.

swagger:response deleteElephpantNotFound
*/
type DeleteElephpantNotFound struct {
}

// NewDeleteElephpantNotFound creates DeleteElephpantNotFound with default headers values
func NewDeleteElephpantNotFound() *DeleteElephpantNotFound {

	return &DeleteElephpantNotFound{}
}

// WriteResponse to the client
func (o *DeleteElephpantNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
