// Code generated by go-swagger; DO NOT EDIT.

package elephpants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/scraly/elephpants-api/pkg/swagger/server/models"
)

// GetElephpantsOKCode is the HTTP code returned for type GetElephpantsOK
const GetElephpantsOKCode int = 200

/*
GetElephpantsOK Return the Gophers list.

swagger:response getElephpantsOK
*/
type GetElephpantsOK struct {
	/*

	 */
	AccessControlAllowOrigin string `json:"Access-Control-Allow-Origin"`

	/*
	  In: Body
	*/
	Payload []*models.Elephpant `json:"body,omitempty"`
}

// NewGetElephpantsOK creates GetElephpantsOK with default headers values
func NewGetElephpantsOK() *GetElephpantsOK {

	return &GetElephpantsOK{}
}

// WithAccessControlAllowOrigin adds the accessControlAllowOrigin to the get elephpants o k response
func (o *GetElephpantsOK) WithAccessControlAllowOrigin(accessControlAllowOrigin string) *GetElephpantsOK {
	o.AccessControlAllowOrigin = accessControlAllowOrigin
	return o
}

// SetAccessControlAllowOrigin sets the accessControlAllowOrigin to the get elephpants o k response
func (o *GetElephpantsOK) SetAccessControlAllowOrigin(accessControlAllowOrigin string) {
	o.AccessControlAllowOrigin = accessControlAllowOrigin
}

// WithPayload adds the payload to the get elephpants o k response
func (o *GetElephpantsOK) WithPayload(payload []*models.Elephpant) *GetElephpantsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get elephpants o k response
func (o *GetElephpantsOK) SetPayload(payload []*models.Elephpant) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetElephpantsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Access-Control-Allow-Origin

	accessControlAllowOrigin := o.AccessControlAllowOrigin
	if accessControlAllowOrigin != "" {
		rw.Header().Set("Access-Control-Allow-Origin", accessControlAllowOrigin)
	}

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Elephpant, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
