// Code generated by go-swagger; DO NOT EDIT.

package elephpants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetElephpantHandlerFunc turns a function with the right signature into a get elephpant handler
type GetElephpantHandlerFunc func(GetElephpantParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetElephpantHandlerFunc) Handle(params GetElephpantParams) middleware.Responder {
	return fn(params)
}

// GetElephpantHandler interface for that can handle valid get elephpant params
type GetElephpantHandler interface {
	Handle(GetElephpantParams) middleware.Responder
}

// NewGetElephpant creates a new http.Handler for the get elephpant operation
func NewGetElephpant(ctx *middleware.Context, handler GetElephpantHandler) *GetElephpant {
	return &GetElephpant{Context: ctx, Handler: handler}
}

/*
	GetElephpant swagger:route GET /elephpant elephpants getElephpant

Get a elephpant by a given name
*/
type GetElephpant struct {
	Context *middleware.Context
	Handler GetElephpantHandler
}

func (o *GetElephpant) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetElephpantParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
