// Code generated by go-swagger; DO NOT EDIT.

package elephpants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostElephpantHandlerFunc turns a function with the right signature into a post elephpant handler
type PostElephpantHandlerFunc func(PostElephpantParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostElephpantHandlerFunc) Handle(params PostElephpantParams) middleware.Responder {
	return fn(params)
}

// PostElephpantHandler interface for that can handle valid post elephpant params
type PostElephpantHandler interface {
	Handle(PostElephpantParams) middleware.Responder
}

// NewPostElephpant creates a new http.Handler for the post elephpant operation
func NewPostElephpant(ctx *middleware.Context, handler PostElephpantHandler) *PostElephpant {
	return &PostElephpant{Context: ctx, Handler: handler}
}

/*
	PostElephpant swagger:route POST /elephpant elephpants postElephpant

Add a new Gopher
*/
type PostElephpant struct {
	Context *middleware.Context
	Handler PostElephpantHandler
}

func (o *PostElephpant) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostElephpantParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostElephpantBody post elephpant body
//
// swagger:model PostElephpantBody
type PostElephpantBody struct {

	// displayname
	// Required: true
	Displayname *string `json:"displayname"`

	// name
	// Required: true
	Name *string `json:"name"`

	// url
	// Required: true
	URL *string `json:"url"`
}

// Validate validates this post elephpant body
func (o *PostElephpantBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDisplayname(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateURL(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostElephpantBody) validateDisplayname(formats strfmt.Registry) error {

	if err := validate.Required("elephpant"+"."+"displayname", "body", o.Displayname); err != nil {
		return err
	}

	return nil
}

func (o *PostElephpantBody) validateName(formats strfmt.Registry) error {

	if err := validate.Required("elephpant"+"."+"name", "body", o.Name); err != nil {
		return err
	}

	return nil
}

func (o *PostElephpantBody) validateURL(formats strfmt.Registry) error {

	if err := validate.Required("elephpant"+"."+"url", "body", o.URL); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post elephpant body based on context it is used
func (o *PostElephpantBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostElephpantBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostElephpantBody) UnmarshalBinary(b []byte) error {
	var res PostElephpantBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
