// Code generated by go-swagger; DO NOT EDIT.

package elephpants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/scraly/elephpants-api/pkg/swagger/server/models"
)

// PutElephpantOKCode is the HTTP code returned for type PutElephpantOK
const PutElephpantOKCode int = 200

/*
PutElephpantOK Updated

swagger:response putElephpantOK
*/
type PutElephpantOK struct {

	/*
	  In: Body
	*/
	Payload *models.Elephpant `json:"body,omitempty"`
}

// NewPutElephpantOK creates PutElephpantOK with default headers values
func NewPutElephpantOK() *PutElephpantOK {

	return &PutElephpantOK{}
}

// WithPayload adds the payload to the put elephpant o k response
func (o *PutElephpantOK) WithPayload(payload *models.Elephpant) *PutElephpantOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put elephpant o k response
func (o *PutElephpantOK) SetPayload(payload *models.Elephpant) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutElephpantOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutElephpantNotFoundCode is the HTTP code returned for type PutElephpantNotFound
const PutElephpantNotFoundCode int = 404

/*
PutElephpantNotFound A elephpant with the specified Name was not found.

swagger:response putElephpantNotFound
*/
type PutElephpantNotFound struct {
}

// NewPutElephpantNotFound creates PutElephpantNotFound with default headers values
func NewPutElephpantNotFound() *PutElephpantNotFound {

	return &PutElephpantNotFound{}
}

// WriteResponse to the client
func (o *PutElephpantNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
