// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Elephpant elephpant
//
// swagger:model Elephpant
type Elephpant struct {

	// displayname
	// Example: My elephpant
	Displayname string `json:"displayname,omitempty"`

	// name
	// Example: my-elephpant
	Name string `json:"name,omitempty"`

	// url
	// Example: https://raw.githubusercontent.com/scraly/elephpants/main/ElePHPant.png
	URL string `json:"url,omitempty"`
}

// Validate validates this elephpant
func (m *Elephpant) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this elephpant based on context it is used
func (m *Elephpant) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Elephpant) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Elephpant) UnmarshalBinary(b []byte) error {
	var res Elephpant
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
